name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-20.04'
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: 'canary'

      - name: Run tests
        run: deno test -A

  lint:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint
